# default to run all experiment
default: exp1 exp2 exp3

exp1:
	cd py && python run_ns2_script.py ex1 && cd ..

exp2:
	cd py && python run_ns2_script.py ex2 && cd ..

exp3:
	cd py && python run_ns2_script.py ex3 && cd ..
