#!/bin/bash

# warning message when input params are erroneous
usage="usage: dnsserver -p <port> -n <name>"

if [ $# != 4 ]
then
    echo "dnsserver: num of params should be 4"
    echo $usage
    exit -1
fi

while [[ $# -gt 0 ]]
do
option="$1"
case $option in
    -p)
        PORT="$2"
        shift
        ;;
    -n)
        NAME="$2"
        shift
        ;;
    -*)
        echo "dnsserver: illegal option -$option"
        echo $usage
        exit -1
        ;;
esac
shift
done

# echo "${PORT}"
# echo "${NAME}"

# start the dns server
java -cp jar/json-simple-1.1.1.jar:. dns.DnsServer "${PORT}" "${NAME}"
